apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: drift-monitor-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: drift-monitor
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
      honorLabels: true
